In [70]:
import pandas as pd

player16 = pd.read_csv("C:/Users/chomjung/Downloads/2020빅콘테스트/선수/2020빅콘테스트_스포츠투아이_제공데이터_선수_2016.csv", encoding = "CP949")
player17 = pd.read_csv("C:/Users/chomjung/Downloads/2020빅콘테스트/선수/2020빅콘테스트_스포츠투아이_제공데이터_선수_2017.csv", encoding = "CP949")
player18 = pd.read_csv("C:/Users/chomjung/Downloads/2020빅콘테스트/선수/2020빅콘테스트_스포츠투아이_제공데이터_선수_2018.csv", encoding = "CP949")
player19 = pd.read_csv("C:/Users/chomjung/Downloads/2020빅콘테스트/선수/2020빅콘테스트_스포츠투아이_제공데이터_선수_2019.csv", encoding = "CP949")
player20 = pd.read_csv("C:/Users/chomjung/Downloads/2020빅콘테스트/선수/2020빅콘테스트_스포츠투아이_제공데이터_선수_2020.csv", encoding = "CP949")

perhitter = pd.read_csv("C:/Users/chomjung/OneDrive - 명지대학교/빅콘테스트2020/데이터 전처리/개인타자 최종.csv", encoding = "CP949")

player = pd.concat([player16,player17,player18,player19,player20])

In [71]:
player_in = player.reset_index(drop=True)
player.columns = ['시즌','선수코드','이름','팀코드','포지션','나이','연봉']
player = player[['시즌','선수코드','팀코드','포지션']]

In [72]:
perhitter2 = pd.merge(left=perhitter, right=player, how='left', on=['시즌','선수코드','팀코드'], sort=False)

In [75]:
perhitter2.to_csv("개인타자1.csv",encoding = 'CP949', index = False)

In [78]:
perhitter2 = perhitter2[['게임키', '일자', '팀코드', '상대팀코드', '더블헤더코드', '초말', '선수코드','포지션', '선발', '타순', '타자',
       '타수', '타점', '득점', '안타', '2루타', '3루타', '홈런', '도루', '도루실패', '희타', '희비',
       '4구', '고4', '사구', '삼진', '병살타', '실책', '잔루', '득점권타율', '득점권타수', '득점권안타',
       '시즌', '단타', '출루율', '장타력', 'ops', '타율', 'BABIP', 'BB/K', 'ISO', 'K%',
       'BB%', 'wOBA', 'wRAA', 'wRC', 'HR%', 'GPA', 'RC', 'RC27', 'SPD', 'XR',
       'SecA']]

In [79]:
perhitter2

,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,선수코드,포지션,선발,타순,...,wOBA,wRAA,wRC,HR%,GPA,RC,RC27,SPD,XR,SecA
0,20160401HHLG0,2016-04-01,HH,LG,0,T,60404,외,0,3,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
1,20160401HHLG0,2016-04-01,LG,HH,0,B,61102,포,1,8,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
2,20160401HHLG0,2016-04-01,LG,HH,0,B,61186,외,1,7,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
3,20160401HHLG0,2016-04-01,LG,HH,0,B,62164,내,0,9,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
4,20160401HHLG0,2016-04-01,HH,LG,0,T,62700,내,1,9,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81097,20200719WOSK0,2020-07-19,SK,WO,0,B,75847,내,1,3,...,0.424664,16.927722,35.569448,0.053279,0.323597,44.520442,8.121973,4.424655,44.774,0.455000
81098,20200719WOSK0,2020-07-19,SK,WO,0,B,76802,내,1,9,...,0.258633,-10.861406,0.171452,0.000000,0.189185,8.159004,2.039751,2.341158,8.842,0.096774
81099,20200719WOSK0,2020-07-19,SK,WO,0,B,77463,내,0,6,...,0.342000,-0.156114,4.409206,0.033898,0.260179,7.941509,5.229774,0.259262,7.320,0.178571
81100,20200719WOSK0,2020-07-19,WO,SK,0,T,78168,내,1,1,...,0.389168,10.457936,31.230144,0.018315,0.293764,42.787961,6.755994,7.958655,44.426,0.366812
81101,20200719WOSK0,2020-07-19,WO,SK,0,T,79456,포,1,6,...,0.363273,2.424822,14.066390,0.000000,0.273254,21.331733,5.877110,3.264740,19.854,0.154412