In [2]:
import pandas as pd

team_hitter = pd.read_csv('C:/Users/chomjung/OneDrive - 명지대학교/빅콘테스트2020/데이터 전처리/팀타자_세이버 매트릭스_합본_8_25.csv', encoding='CP949')
hitter = pd.read_csv('C:/Users/chomjung/OneDrive - 명지대학교/빅콘테스트2020/데이터 전처리/개인타자_세이버 매트릭스_합본_8_25.csv', encoding='CP949')

In [21]:
hitter

,Unnamed: 0,게임키,일자,팀코드,상대팀코드,더블헤더코드,초말,선수코드,선발,타순,...,BB%,wOBA,wRAA,wRC,HR%,GPA,RC,RC27,SPD,XR
0,0,20160401HHLG0,2016-04-01,HH,LG,0,T,60404,0,3,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
1,1,20160401HHLG0,2016-04-01,LG,HH,0,B,61102,1,8,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
2,2,20160401HHLG0,2016-04-01,LG,HH,0,B,61186,1,7,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
3,3,20160401HHLG0,2016-04-01,LG,HH,0,B,62164,0,9,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
4,4,20160401HHLG0,2016-04-01,HH,LG,0,T,62700,1,9,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81097,81097,20200719WOSK0,2020-07-19,SK,WO,0,B,75847,1,3,...,0.143443,0.424664,16.927722,35.569448,0.053279,0.323597,44.520442,8.121973,4.424655,44.774
81098,81098,20200719WOSK0,2020-07-19,SK,WO,0,B,76802,1,9,...,0.082759,0.258633,-10.861406,0.171452,0.000000,0.189185,8.159004,2.039751,2.341158,8.842
81099,81099,20200719WOSK0,2020-07-19,SK,WO,0,B,77463,0,6,...,0.050847,0.342000,-0.156114,4.409206,0.033898,0.260179,7.941509,5.229774,0.259262,7.320
81100,81100,20200719WOSK0,2020-07-19,WO,SK,0,T,78168,1,1,...,0.139194,0.389168,10.457936,31.230144,0.018315,0.293764,42.787961,6.755994,7.958655,44.426
81101,81101,20200719WOSK0,2020-07-19,WO,SK,0,T,79456,1,6,...,0.072368,0.363273,2.424822,14.066390,0.000000,0.273254,21.331733,5.877110,3.264740,19.854

In [3]:
def SecA(row):
    previous = team_hitter[(team_hitter['시즌'] == row['시즌']) & (team_hitter['팀코드'] == row['팀코드']) & (team_hitter['일자'] < row['일자'])]
    if len(previous) == 0:
        row['SecA'] = 0
        return row
    previous_sum = previous.sum()
    up = previous_sum['4구']+(previous_sum['2루타']+previous_sum['3루타']*2+previous_sum['홈런']*3)+previous_sum['도루']-previous_sum['도루실패']
    down = previous_sum['타수']
    if down == 0:
        row['SecA'] = 0
        return row
    row['SecA'] = up/down
    return row
def perSecA(row):
    previous = hitter[hitter['선수코드'] == row['선수코드']].copy()
    previous = previous[(previous['시즌'] == row['시즌']) &(previous['일자'] < row['일자'])]
    previous_sum = previous.sum()
    if len(previous) == 0:
        row['SecA'] = 0
        return row
    up = previous_sum['4구']+(previous_sum['2루타']+previous_sum['3루타']*2+previous_sum['홈런']*3)+previous_sum['도루']-previous_sum['도루실패']
    down = previous_sum['타수']    
    if down == 0:
        row['SecA'] = 0
        return row
    row['SecA'] = up/down   
    return row

In [7]:
team_hitter = team_hitter.apply(SecA, axis=1)

In [4]:
hitter = hitter.apply(perSecA, axis = 1)

In [8]:
team_hitter.to_csv("./팀타자 최종.csv",encoding = 'CP949', index = False)

In [1]:
hitter

NameError: name 'hitter' is not defined