<a href="https://colab.research.google.com/github/CHO-MINJUNG/BigContest2020/blob/master/%EC%8B%9C%EA%B3%84%EC%97%B4%EC%98%88%EC%B8%A1_%EB%AA%A8%EB%8D%B8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import auth
auth.authenticate_user()

from google.colab import drive
drive.mount('/content/gdrive', force_remount=False)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
4/3wF2rvim4Wrt6K9bHlPJ8THFUDKl_TUJ8qCYavk4j52UoTyZcdv_pns
Mounted at /content/gdrive

In [44]:
import pandas as pd
import numpy as np
teamhitter = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/3차_최종_최근_상대_팀타자.csv', encoding='utf-8-sig')

In [45]:
import tensorflow as tf
from tensorflow.keras import layers

print('tensorflow version: {}'.format(tf.__version__))
print('GPU 사용 가능 여부: {}'.format(tf.test.is_gpu_available()))

tensorflow version: 2.3.0
GPU 사용 가능 여부: True

In [25]:
teamhitter.head(30)

   팀코드 상대팀코드  타자  타수  타점  ...  상대최근RC27  상대최근XR   상대최근SPD  상대최근SecA   상대최근PSN
0   LG    HH  47  42   4  ...  0.000000   0.000  0.000000  0.000000  0.000000
1   HH    LG  52  46   4  ...  0.000000   0.000  0.000000  0.000000  0.000000
2   NC    HT  36  30   5  ...  0.000000   0.000  0.000000  0.000000  0.000000
3   HT    NC  38  34   3  ...  0.000000   0.000  0.000000  0.000000  0.000000
4   SK    KT  36  36   4  ...  0.000000   0.000  0.000000  0.000000  0.000000
5   KT    SK  42  36   7  ...  0.000000   0.000  0.000000  0.000000  0.000000
6   WO    LT  36  30   1  ...  0.000000   0.000  0.000000  0.000000  0.000000
7   LT    WO  39  37   1  ...  0.000000   0.000  0.000000  0.000000  0.000000
8   SS    OB  35  32   1  ...  0.000000   0.000  0.000000  0.000000  0.000000
9   OB    SS  37  31   4  ...  0.000000   0.000  0.000000  0.000000  0.000000
10  LG    HH  49  40   8  ...  2.878534   4.262  5.331588  0.238095  1.333333
11  HH    LG  50  43   7  ...  3.478028   4.660  1.953175  0.108696  0.000000
12  NC    HT  36  33   3  ...  7.312866   6.228  0.959023  0.433333  0.000000
13  HT    NC  39  33   4  ...  4.187754   4.170  1.741822  0.264706  0.000000
14  SK    KT  44  37   4  ...  4.311333   4.274  2.052381  0.222222  0.000000
15  KT    SK  41  34   3  ...  6.631357   7.184  5.922600  0.305556  2.000000
16  WO    LT  35  30   5  ...  1.980806   2.442  3.165632  0.133333  0.000000
17  LT    WO  39  34   3  ...  3.822503   3.672  1.150047  0.135135  0.000000
18  SS    OB  41  36  10  ...  2.049333   1.932  0.574700  0.062500  0.000000
19  OB    SS  42  38   6  ...  4.193562   5.226  4.001460  0.322581  2.000000
20  SK    KT  38  32   4  ...  5.063151  10.366  3.199641  0.287671  2.000000
21  KT    SK  40  33   5  ...  4.175606   9.520  3.325489  0.214286  2.000000
22  WO    LT  42  34   6  ...  3.235923   6.194  3.191984  0.133333  0.000000
23  LT    WO  43  38   5  ...  3.790172   7.660  3.061745  0.197183  0.000000
24  HT    LG  31  28   4  ...  0.000000   0.000  0.000000  0.000000  0.000000
25  LG    HT  35  34   1  ...  0.000000   0.000  0.000000  0.000000  0.000000
26  OB    NC  39  28   5  ...  0.000000   0.000  0.000000  0.000000  0.000000
27  NC    OB  37  31   2  ...  0.000000   0.000  0.000000  0.000000  0.000000
28  LT    SK  34  30   2  ...  0.000000   0.000  0.000000  0.000000  0.000000
29  SK    LT  35  30   1  ...  0.000000   0.000  0.000000  0.000000  0.000000

[30 rows x 44 columns]

In [46]:
teamhitter = teamhitter[['팀코드', '득점','상대최근OBP', '상대최근SLG', '상대최근ops', '상대최근타율', '상대최근ISO', '상대최근BABIP',
       '상대최근BB/K', '상대최근K%', '상대최근BB%', '상대최근wOBA', '상대최근wRAA', '상대최근wRC',
       '상대최근HR%', '상대최근GPA', '상대최근RC', '상대최근RC27', '상대최근XR', '상대최근SPD',
       '상대최근SecA', '상대최근PSN']]

In [47]:
teamhitterNC = teamhitter[teamhitter['팀코드']=='NC']
teamhitterNC.reset_index(drop=True)
scoreNC = teamhitterNC['득점']
del teamhitterNC['득점']

teamhitterSK = teamhitter[teamhitter['팀코드']=='SK']
teamhitterSK.reset_index(drop=True)
scoreSK = teamhitterSK['득점']
del teamhitterSK['득점']

teamhitterKT = teamhitter[teamhitter['팀코드']=='KT']
teamhitterKT.reset_index(drop=True)
scoreKT = teamhitterKT['득점']
del teamhitterKT['득점']

teamhitterHT = teamhitter[teamhitter['팀코드']=='HT']
teamhitterHT.reset_index(drop=True)
scoreHT = teamhitterHT['득점']
del teamhitterHT['득점']

teamhitterLT = teamhitter[teamhitter['팀코드']=='LT']
teamhitterLT.reset_index(drop=True)
scoreLT = teamhitterLT['득점']
del teamhitterLT['득점']

teamhitterWO = teamhitter[teamhitter['팀코드']=='WO']
teamhitterWO.reset_index(drop=True)
scoreWO = teamhitterWO['득점']
del teamhitterWO['득점']

teamhitterOB = teamhitter[teamhitter['팀코드']=='OB']
teamhitterOB.reset_index(drop=True)
scoreOB = teamhitterOB['득점']
del teamhitterOB['득점']

teamhitterHH = teamhitter[teamhitter['팀코드']=='HH']
teamhitterHH.reset_index(drop=True)
scoreHH = teamhitterHH['득점']
del teamhitterHH['득점']

teamhitterLG = teamhitter[teamhitter['팀코드']=='LG']
teamhitterLG.reset_index(drop=True)
scoreLG = teamhitterLG['득점']
del teamhitterLG['득점']

teamhitterSS = teamhitter[teamhitter['팀코드']=='SS']
teamhitterSS.reset_index(drop=True)
scoreSS = teamhitterSS['득점']
del teamhitterSS['득점']

In [53]:
NCtrain =list( teamhitterNC.values.tolist() ) 
NCtrain_x = np.array(NCtrain)
NCtrain_y = np.array(scoreNC.values.tolist())

In [58]:
NCtrain_x = NCtrain_x.reshape(NCtrain_x.shape[0],NCtrain_x.shape[1],1)
NCtrain_x.shape

(636, 21, 1)

In [63]:
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, LSTM
model = Sequential()

model.add(LSTM(32, input_shape = (21,1), activation = 'relu'))
model.add(Dense(32))

model.summary()

model.compile(loss='mse', optimizer = 'adam', metrics = ['mse'])
model.fit(NCtrain_x,NCtrain_y,epochs = 30, batch_size=9)

WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_3 (LSTM)                (None, 32)                4352
_________________________________________________________________
dense_3 (Dense)              (None, 32)                1056
=================================================================
Total params: 5,408
Trainable params: 5,408
Non-trainable params: 0
_________________________________________________________________
Epoch 1/30

UnimplementedError: ignored

In [60]:
batch_size = 9
max_epochs = 30
learning_rate = 4e-5
hidden_sizes = [128, 128]

2       5
12      3
27      2
35      0
45      8
       ..
6288    4
6298    9
6303    3
6313    6
6323    8
Name: 득점, Length: 636, dtype: int64

In [ ]:
def preprocess():
  # 1차_최종_공통 : 시즌, 홈어웨이, 경기간간격, 득점, 실점, 승패
  general = pd.read_csv('./gdrive/My Drive/빅콘테스트2020/1차_최종_데이터/1차_최종_공통.csv')
  general = general[general['팀코드']=='NC']
  general = general[['게임키', '경기간간격','득점','실점','결과']]
  general['시즌'] = general['게임키'].apply(lambda x:int(x[:4]))
  general['홈어웨이'] = general['게임키'].apply(lambda x:0 if x[-3:-1]=='NC' else 1)
  general=general.set_index('게임키')
  # 팀타자 : 기준팀 wRC
  hitter = teamhitter
  hitter_vs = hitter[hitter['상대팀코드']=='NC']
  hitter = hitter[hitter['팀코드']=='NC']
  hitter = hitter[['게임키', '상대최근RC']]
  hitter_vs = hitter_vs[['게임키', '상대최근RC']]
  hitter=hitter.set_index('게임키')
  hitter_vs=hitter_vs.set_index('게임키')
  hitter_vs=hitter_vs.add_prefix('vs_')
  df = pd.concat([general, hitter,hitter_vs], axis=1)
  df= df[['시즌','경기간간격','홈어웨이','상대최근RC','vs_상대최근RC','득점','실점','결과']]
  df['결과'] = df['결과'].apply(lambda x : 0 if x =='W' else 1)
  return df

In [ ]:
df = preprocess()
df.head()

                 시즌  경기간간격  홈어웨이    상대최근RC  vs_상대최근RC  득점  실점  결과
20160401HTNC0  2016    0.0     0  0.000000   0.000000   5   4   0
20160402HTNC0  2016    1.0     0  6.229478   4.187754   3   4   1
20160405NCOB0  2016    3.0     1  0.000000   0.000000   2   6   1
20160406NCOB0  2016    1.0     1  1.818505   5.305242   0   2   1
20160407NCOB0  2016    1.0     1  0.241434   6.986094   8   2   0

In [ ]:
def create_dataset(signal_data, look_back=1):
    dataX, dataY = [], []
    for i in range(len(signal_data)-look_back):
        dataX.append(signal_data[i:(i+look_back), 0])
        dataY.append(signal_data[i + look_back, 0])
    return np.array(dataX), np.array(dataY)